### PR TITLE
Stop faux socket reuse in httplib and wallet api (#703)

### LINKED ISSUE #703: You can open two wallet-api's on the same port with no issue
Since the port is already in use, this should fail. Probably need to tweak something in external/cpp-httlib

### PR DESCRIPTION
**Pull request by brandonlehmann**
Resolves #703

### CODE REVIEW

File: external/cpp-httplib/httplib.h [hunk 1]
```diff
@@ -610,7 +610,7 @@ socket_t create_socket(const char* host, int port, Fn fn, int socket_flags = 0)
 
        // Make 'reuse address' option available
        int yes = 1;
-       setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (char*)&yes, sizeof(yes));
+       setsockopt(sock, SOL_SOCKET, SO_EXCLUSIVEADDRUSE, (char*)&yes, sizeof(yes));
```
Comment (zpalmtree) [inline external/cpp-httplib/httplib.h]: Doesn't compile on Linux: `error: use of undeclared identifier 'SO_EXCLUSIVEADDRUSE'`. We don't need this on Linux anyway, so perhaps use an ifdef.

File: src/WalletApi/WalletApi.cpp [hunk 2]
```diff
@@ -41,6 +42,8 @@ int main(int argc, char **argv)
         /* Launch the API */
         apiThread = std::thread(&ApiDispatcher::start, api.get());
 
+        std::this_thread::sleep_for(std::chrono::milliseconds(250));
```
Comment (zpalmtree) [inline src/WalletApi/WalletApi.cpp]: Can we add a comment explaining the reason for this sleep.

File: src/WalletApi/ApiDispatcher.cpp [hunk 3]
```diff
@@ -208,7 +208,14 @@ ApiDispatcher::ApiDispatcher(
...
 void ApiDispatcher::start()
 {
-    m_server.listen(m_host, m_port);
+    if (!m_server.listen(m_host, m_port))
+    {
+      std::ostringstream oss;
+      oss << "Could not bind service to " << m_host << ":" << m_port 
+          << std::endl << "Is another service using this address and port?";
+      std::cout << std::endl << oss.str() << std::endl << std::endl;
+      throw std::runtime_error(oss.str());
```
Comment (zpalmtree) [inline src/WalletApi/ApiDispatcher.cpp]: I assume this exception isn't being caught, since the catch is in another thread?
If it is, do we need to print the message twice?
If not, can we use `exit()` instead?

File: src/WalletApi/ApiDispatcher.cpp [hunk 4]
```diff
@@ -208,7 +208,14 @@ ApiDispatcher::ApiDispatcher(
 
 void ApiDispatcher::start()
 {
-    m_server.listen(m_host, m_port);
+    if (!m_server.listen(m_host, m_port))
+    {
+      std::ostringstream oss;
+      oss << "Could not bind service to " << m_host << ":" << m_port 
+          << std::endl << "Is another service using this address and port?";
```
Comment (zpalmtree) [inline src/WalletApi/ApiDispatcher.cpp]: Minor complaint, but it's preferable to use `\n` instead of `std::endl` where possible - `std::endl` flushes the stream as well as printing a newline, which is unneeded here.

File: src/WalletApi/ApiDispatcher.cpp (hunk 3 above)
Comment (brandonlehmann) [reply src/WalletApi/ApiDispatcher.cpp]: True. It doesn’t get caught as it’s on another thread and passing in global exception pointed felt weird. 

It doesn’t actually print twice as the throw isn’t caught in the main thread. 

Exit would only exit the thread.

File: src/WalletApi/ApiDispatcher.cpp (hunk 4 above)
Comment (brandonlehmann) [reply src/WalletApi/ApiDispatcher.cpp]: Fair enough

Comment (brandonlehmann) [reply src/WalletApi/ApiDispatcher.cpp]: Fair enough

File: external/cpp-httplib/httplib.h (hunk 1 above)
Comment (brandonlehmann) [reply external/cpp-httplib/httplib.h]: Adding ifdef

File: src/WalletApi/WalletApi.cpp (hunk 2 above)
Comment (brandonlehmann) [reply src/WalletApi/WalletApi.cpp]: No. Lol

Comment (RocksteadyTC) [reply src/WalletApi/WalletApi.cpp]: I can add one

Comment (brandonlehmann) [reply src/WalletApi/WalletApi.cpp]: I see what you did there.

File: src/WalletApi/ApiDispatcher.cpp (hunk 3 above)
Comment (zpalmtree) [reply src/WalletApi/ApiDispatcher.cpp]: Exit terminates the whole program on my machine, and the docs agree:
`Terminates the process normally, performing the regular cleanup for terminating programs.`
http://www.cplusplus.com/reference/cstdlib/exit/

File: src/WalletApi/WalletApi.cpp (hunk 2 above)
Comment (RocksteadyTC) [reply src/WalletApi/WalletApi.cpp]: image
